# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 82d6ec3a06ec42b63b6cb33b5c9c42c84ad6bbe1d4e09b8bc4bb0ec418ccd318718e8d7635533e2cb8dfae3b25f511af93e4be8a4cce7627de03c61b5ee394e7

test:
  secret_key_base: 3fb7374fed3f6dab7a085d77f95ec1748f0300a576ba919cb727bcce4ef7c6ae7acccd9561605e97422afbc5747d025218d050b0dfdfce2c2572b233a12e5bff

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
